spring:
  flyway:
    enabled: true
  datasource:
    url: ${db_url:jdbc:postgresql://localhost:3307/learn_jwt}
    username: ${db_username:postgres}
    password: ${db_password:1234}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
server:
  error:
    include-stacktrace: never
    include-message: always
    whitelabel:
      enabled: true